data:
  raw:
    train:
      nc_down: 'data/raw/ecsmpf_round1_train_20210625/round1_train_nc_down.csv'
      nc_exceptions: 'data/raw/ecsmpf_round1_train_20210625/round1_train_nc_exceptions.csv'
      nc_info: 'data/raw/ecsmpf_round1_train_20210625/round1_train_nc_info.csv'
      nc_sample_label: 'data/raw/ecsmpf_round1_train_20210625/round1_train_nc_sample_label.csv'
    A_test:
      nc_exceptions: 'data/raw/ecsmpf_round1_A_test_20210625/round1_A_test_nc_exceptions.csv'
      nc_info: 'data/raw/ecsmpf_round1_A_test_20210625/round1_A_test_nc_info.csv'
      nc_sample_label: 'data/raw/ecsmpf_round1_A_test_20210625/round1_A_test_nc_sample_label.csv'
    B_test:
      nc_exceptions: 'data/raw/ecsmpf_round1_B_test_20210625/round1_B_test_nc_exceptions.csv'
      nc_info: 'data/raw/ecsmpf_round1_B_test_20210625/round1_B_test_nc_info.csv'
      nc_sample_label: 'data/raw/ecsmpf_round1_B_test_20210625/round1_B_test_nc_sample_label.csv'
  process:
    train:
      nc_exceptions_key_ip_name_value_timelist: 'data/process/ecsmpf_round1_train_20210625/round1_train_nc_exceptions_key_ip_name_value_timelist.csv'
      nc_exceptions_key_ip_column_name_value_timelist: 'data/process/ecsmpf_round1_train_20210625/round1_train_nc_exceptions_key_ip_column_name_value_timelist.csv'
    aug_train:
      nc_sample_label: 'data/process/ecsmpf_round1_aug_train_20210625/round1_aug_train_nc_sample_label.csv'
      nc_exceptions_key_ip_name_value_timelist: 'data/process/ecsmpf_round1_aug_train_20210625/round1_aug_train_nc_exceptions_key_ip_name_value_timelist'
      nc_exceptions_key_ip_column_name_value_timelist: data/process/ecsmpf_round1_aug_train_20210625/round1_aug_train_nc_exceptions_key_ip_column_name_value_timelist.csv
    A_test:
      nc_sample_pseudo_label: 'data/process/ecsmpf_round1_A_test_20210625/round1_test_nc_sample_pseudo_label.csv'
      nc_exceptions_key_ip_name_value_timelist: 'data/process/ecsmpf_round1_A_test_20210625/round1_test_nc_exceptions_key_ip_name_value_timelist.csv'
      nc_exceptions_key_ip_column_name_value_timelist: 'data/process/ecsmpf_round1_A_test_20210625/round1_test_nc_exceptions_key_ip_column_name_value_timelist.csv'
    B_test:
      nc_sample_pseudo_label: 'data/process/ecsmpf_round1_B_test_20210625/round1_test_nc_sample_pseudo_label.csv'
      nc_exceptions_key_ip_name_value_timelist: 'data/process/ecsmpf_round1_B_test_20210625/round1_test_nc_exceptions_key_ip_name_value_timelist.csv'
      nc_exceptions_key_ip_column_name_value_timelist: 'data/process/ecsmpf_round1_B_test_20210625/round1_test_nc_exceptions_key_ip_column_name_value_timelist.csv'

  features:
    train:
      n_exceptions: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions.csv'
      n_exceptions_recent_week: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions_recent_week.csv'
      n_exceptions_with_nc_info: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions_with_nc_info.csv'
      n_exceptions_recent_week_with_nc_info: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions_recent_week_with_nc_info.csv'
      n_exceptions_recent_week_with_diff: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions_recent_week_with_diff.csv'
      n_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_train_20210625/round1_train_n_exceptions_recent_week_filter.csv'
      rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_train_20210625/round1_train_rate_exceptions_recent_week_filter.csv'
      sum_rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_train_20210625/round1_train_sum_rate_exceptions_recent_week_filter.csv'
    aug_train:
      n_exceptions_recent_week: 'data/features/ecsmpf_round1_aug_train_20210625/round1_aug_train_n_exceptions_recent_week.csv'
      n_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_aug_train_20210625/round1_aug_train_n_exceptions_recent_week_filter.csv'
      sum_rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_aug_train_20210625/round1_aug_train_sum_rate_exceptions_recent_week_filter.csv'
      rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_aug_train_20210625/round1_aug_train_rate_exceptions_recent_week_filter.csv'
    A_test:
      n_exceptions: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions.csv'
      n_exceptions_recent_week: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions_recent_week.csv'
      n_exceptions_with_nc_info: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions_with_nc_info.csv'
      n_exceptions_recent_week_with_nc_info: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions_recent_week_with_nc_info.csv'
      n_exceptions_recent_week_with_diff: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions_recent_week_with_diff.csv'
      n_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_n_exceptions_recent_week_filter.csv'
      rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_rate_exceptions_recent_week_filter.csv'
      sum_rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_A_test_20210625/round1_test_sum_rate_exceptions_recent_week_filter.csv'
    B_test:
      n_exceptions_recent_week: 'data/features/ecsmpf_round1_B_test_20210625/round1_test_n_exceptions_recent_week.csv'
      n_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_B_test_20210625/round1_test_n_exceptions_recent_week_filter.csv'
      sum_rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_B_test_20210625/round1_test_sum_rate_exceptions_recent_week_filter.csv'
      rate_exceptions_recent_week_filter: 'data/features/ecsmpf_round1_B_test_20210625/round1_test_rate_exceptions_recent_week_filter.csv'

result_dir: 'result'

exception_name:
  train: ['exception_name_10', 'exception_name_11', 'exception_name_12', 'exception_name_14', 'exception_name_15', 'exception_name_16', 'exception_name_17', 'exception_name_18', 'exception_name_19', 'exception_name_2', 'exception_name_20', 'exception_name_21', 'exception_name_22', 'exception_name_24', 'exception_name_25', 'exception_name_26', 'exception_name_27', 'exception_name_28', 'exception_name_29', 'exception_name_3', 'exception_name_30', 'exception_name_31', 'exception_name_32', 'exception_name_33', 'exception_name_34', 'exception_name_35', 'exception_name_36', 'exception_name_37', 'exception_name_38', 'exception_name_39', 'exception_name_4', 'exception_name_40', 'exception_name_41', 'exception_name_42', 'exception_name_43', 'exception_name_44', 'exception_name_45', 'exception_name_46', 'exception_name_47', 'exception_name_48', 'exception_name_49', 'exception_name_5', 'exception_name_50', 'exception_name_51', 'exception_name_52', 'exception_name_53', 'exception_name_54', 'exception_name_55', 'exception_name_56', 'exception_name_57', 'exception_name_58', 'exception_name_59', 'exception_name_6', 'exception_name_60', 'exception_name_7', 'exception_name_8', 'exception_name_9']
  test: ['exception_name_10', 'exception_name_11', 'exception_name_12', 'exception_name_14', 'exception_name_15', 'exception_name_16', 'exception_name_17', 'exception_name_18', 'exception_name_19', 'exception_name_2', 'exception_name_20', 'exception_name_21', 'exception_name_22', 'exception_name_25', 'exception_name_26', 'exception_name_27', 'exception_name_28', 'exception_name_29', 'exception_name_3', 'exception_name_30', 'exception_name_31', 'exception_name_32', 'exception_name_33', 'exception_name_34', 'exception_name_35', 'exception_name_36', 'exception_name_37', 'exception_name_38', 'exception_name_39', 'exception_name_4', 'exception_name_40', 'exception_name_41', 'exception_name_42', 'exception_name_43', 'exception_name_45', 'exception_name_46', 'exception_name_47', 'exception_name_48', 'exception_name_49', 'exception_name_5', 'exception_name_51', 'exception_name_52', 'exception_name_53', 'exception_name_54', 'exception_name_56', 'exception_name_57', 'exception_name_58', 'exception_name_59', 'exception_name_6', 'exception_name_60', 'exception_name_7', 'exception_name_8', 'exception_name_9']

nc_info_name:
  train: []
  test: []

model:
  random_state: 2021
  hyperameters:
    xgboost:
      max_depth: 10 
      learning_rate: 0.024
      n_estimators: 242
      verbosity: 1
      objective: 'binary:logistic'
      n_jobs: 4
      gamma: 2.735
      min_child_weight: 0.5
      max_delta_step: 0
      subsample: 0.209
      colsample_bytree: 0.5
      # subsample: 1
      # colsample_bytree: 1
      colsample_bylevel: 1
      reg_alpha: 0.3576
      reg_lambda: 0.8618
      scale_pos_weight: 1
      # random_state: 2021
      missing: 0
      importance_type: 'total_gain'
      use_label_encoder: False
      eval_metric: 'logloss'
    logistic_regression:
      penalty: 'l2'
      dual: False
      tol: 0.0001
      C: 1.0
      fit_intercept: True
      intercept_scaling: 1 
      # class_weight: None
      # solver: 'lbfgs'
      solver: 'sag'
      max_iter: 100 
      multi_class: 'auto'
      verbose: 0 
      warm_start: False
      # n_jobs: 4
      # l1_ratio: None

    im_ensemble:
      built_in:
        sampling_strategy: 0.25
        n_jobs: 4
        verbose: 1
        n_estimators: 100
      custom:
        base_estimator: 'xgboost'

